import { readFileSync, writeFileSync } from "fs";

let script = readFileSync("scripts/generate-native-contracts.mjs", "utf8");

if (!script.includes("manifests/application-commands.json")) {
  script = script.replace(
    'const inbound = readJson("manifests/native-inbound-events.schema.json");',
    'const inbound = readJson("manifests/native-inbound-events.schema.json");\nconst appCommands = readJson("manifests/application-commands.json");'
  );

  const newOutputs = `
put("src/api/generated/applicationCommands.generated.ts", \`// Generated by scripts/generate-native-contracts.mjs. Do not edit.
export const COMMAND_IDS = \${JSON.stringify(appCommands.commands.map(c => c.id), null, 2)} as const;
export type GeneratedCommandId = (typeof COMMAND_IDS)[number];

export const COMMAND_DEFINITIONS: Record<string, any> = \${JSON.stringify(
  Object.fromEntries(appCommands.commands.map(c => [c.id, c])), null, 2
)};

export const CLASSIC_MENU_GROUPS: any[] = \${JSON.stringify(
  appCommands.menus.filter(m => !m.platforms || m.platforms.includes("windows") || m.platforms.includes("linux")).map(m => {
    // clean platforms
    const { platforms, ...rest } = m;
    if (rest.items) {
      rest.items = rest.items.map(item => {
        const { platforms, ...itemRest } = item;
        return itemRest;
      });
    }
    return rest;
  }), null, 2
)};

export const CLASSIC_TOOLBAR_GROUPS: any[] = \${JSON.stringify(appCommands.toolbarGroups, null, 2)};
export const CLASSIC_TOOLBAR_ORDER: string[] = \${JSON.stringify(appCommands.toolbarGroups.flatMap(g => g.items), null, 2)};
\`);

// Rust macOS Menu
const macosMenus = appCommands.menus.filter(m => !m.platforms || m.platforms.includes("macos"));

const buildMenuBlock = (menu, varName) => {
  let rust = \`    let \${varName} = SubmenuBuilder::new(app, "\${menu.label}")\\n\`;
  for (const item of menu.items) {
    if (item.kind === "command") {
      const command = appCommands.commands.find(c => c.id === item.id);
      const acc = command.macOSAccelerator ? \`Some("\${command.macOSAccelerator}")\` : "None";
      rust += \`        .item(&menu_command(app, "\${command.id}", "\${command.label}", \${acc})?)\\n\`;
    } else if (item.kind === "separator") {
      rust += \`        .separator()\\n\`;
    } else if (item.kind === "submenu") {
      // not handling deep submenus for now as there are none in macos menu
    } else if (item.kind.startsWith("macos-")) {
      const predefined = item.kind.replace("macos-", "").replace(/-/g, "_");
      rust += \`        .\${predefined}()\\n\`;
    }
  }
  rust += \`        .build()?;\\n\`;
  return rust;
};

let macosRust = \`// Generated by scripts/generate-native-contracts.mjs. Do not edit.
pub fn build_macos_menu(app: &tauri::AppHandle<tauri::Wry>) -> tauri::Result<tauri::menu::Menu<tauri::Wry>> {
    use tauri::menu::SubmenuBuilder;
\`;

const menuVars = [];
for (let i = 0; i < macosMenus.length; i++) {
  const varName = \`menu_\${i}\`;
  menuVars.push(varName);
  macosRust += buildMenuBlock(macosMenus[i], varName);
}

macosRust += \`    tauri::menu::MenuBuilder::new(app)\\n        .items(&[\${menuVars.map(v => \`&\${v}\`).join(", ")}])\\n        .build()\\n}\\n\`;

put("src-tauri/src/generated/macos_menu.generated.rs", macosRust);
`;

  script = script.replace(
    'put("src/app/generated/archiveFileTypes.generated.json"',
    `${newOutputs}\nput("src/app/generated/archiveFileTypes.generated.json"`
  );

  writeFileSync("scripts/generate-native-contracts.mjs", script);
}
