// Generated by scripts/generate-native-contracts.mjs. Do not edit.
use windows::core::{GUID, PCWSTR, w};
use zmanager_shell_contract::ShellActionKind;

pub(crate) const OPEN_ARCHIVE_CLSID: GUID = GUID::from_u128(0x8ac91dd4_b918_4118_9635_9407a4731972);
pub(crate) const ADD_TO_ARCHIVE_CLSID: GUID = GUID::from_u128(0x8bd7f398_a6c3_40a2_a4f8_725e0d671366);
pub(crate) const ADD_TO_ZIP_CLSID: GUID = GUID::from_u128(0xaa751926_e80f_47a5_9e03_dfa87926f23a);
pub(crate) const ADD_TO_TZAP_CLSID: GUID = GUID::from_u128(0xbeeb01f9_5243_4f96_9bb1_54fa4c250cde);
pub(crate) const ADD_TO_SEVEN_Z_CLSID: GUID = GUID::from_u128(0xc910bf28_3121_48f7_a8a1_2f4d8f587ce8);
pub(crate) const ADD_TO_TZST_CLSID: GUID = GUID::from_u128(0x9838e6cb_f43e_4fc9_96f1_7f0f4bdbb728);
pub(crate) const ADD_TO_TGZ_CLSID: GUID = GUID::from_u128(0x7f3e8a1b_2c4d_45f6_9a7b_8c9d0e1f2a3b);
pub(crate) const EXTRACT_HERE_CLSID: GUID = GUID::from_u128(0x5e7c0abe_ac4c_4d4b_bedd_a9133d7f80d4);
pub(crate) const EXTRACT_TO_FOLDER_CLSID: GUID = GUID::from_u128(0xae04555b_2c6b_42c1_870a_9b15e1e0b82b);

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum ExplorerAction {
    Open,
    Compress,
    CompressZip,
    CompressTzap,
    CompressSevenZ,
    CompressTarZst,
    CompressTarGz,
    ExtractHere,
    ExtractToFolder,
}

#[cfg(test)]
pub(crate) const ALL_EXPLORER_ACTIONS: &[ExplorerAction] = &[
    ExplorerAction::Open,
    ExplorerAction::Compress,
    ExplorerAction::CompressZip,
    ExplorerAction::CompressTzap,
    ExplorerAction::CompressSevenZ,
    ExplorerAction::CompressTarZst,
    ExplorerAction::CompressTarGz,
    ExplorerAction::ExtractHere,
    ExplorerAction::ExtractToFolder,
];

impl ExplorerAction {
    pub(crate) fn from_clsid(clsid: &GUID) -> Option<Self> {
        match *clsid {
            OPEN_ARCHIVE_CLSID => Some(Self::Open),
            ADD_TO_ARCHIVE_CLSID => Some(Self::Compress),
            ADD_TO_ZIP_CLSID => Some(Self::CompressZip),
            ADD_TO_TZAP_CLSID => Some(Self::CompressTzap),
            ADD_TO_SEVEN_Z_CLSID => Some(Self::CompressSevenZ),
            ADD_TO_TZST_CLSID => Some(Self::CompressTarZst),
            ADD_TO_TGZ_CLSID => Some(Self::CompressTarGz),
            EXTRACT_HERE_CLSID => Some(Self::ExtractHere),
            EXTRACT_TO_FOLDER_CLSID => Some(Self::ExtractToFolder),
            _ => None,
        }
    }

    pub(crate) fn clsid(self) -> GUID {
        match self {
            Self::Open => OPEN_ARCHIVE_CLSID,
            Self::Compress => ADD_TO_ARCHIVE_CLSID,
            Self::CompressZip => ADD_TO_ZIP_CLSID,
            Self::CompressTzap => ADD_TO_TZAP_CLSID,
            Self::CompressSevenZ => ADD_TO_SEVEN_Z_CLSID,
            Self::CompressTarZst => ADD_TO_TZST_CLSID,
            Self::CompressTarGz => ADD_TO_TGZ_CLSID,
            Self::ExtractHere => EXTRACT_HERE_CLSID,
            Self::ExtractToFolder => EXTRACT_TO_FOLDER_CLSID,
        }
    }

    pub(crate) fn title(self) -> PCWSTR {
        match self {
            Self::Open => w!("Open archive"),
            Self::Compress => w!("Add to archive..."),
            Self::CompressZip => w!("Add to .zip"),
            Self::CompressTzap => w!("Add to .tzap"),
            Self::CompressSevenZ => w!("Add to .7z"),
            Self::CompressTarZst => w!("Add to .tzst"),
            Self::CompressTarGz => w!("Add to .tgz"),
            Self::ExtractHere => w!("Extract Here"),
            Self::ExtractToFolder => w!("Extract to Archive Folder"),
        }
    }

    pub(crate) fn shell_action(self) -> ShellActionKind {
        match self {
            Self::Open => ShellActionKind::Open,
            Self::Compress => ShellActionKind::Compress,
            Self::CompressZip => ShellActionKind::CompressZip,
            Self::CompressTzap => ShellActionKind::CompressTzap,
            Self::CompressSevenZ => ShellActionKind::CompressSevenZ,
            Self::CompressTarZst => ShellActionKind::CompressTarZst,
            Self::CompressTarGz => ShellActionKind::CompressTarGz,
            Self::ExtractHere => ShellActionKind::ExtractHere,
            Self::ExtractToFolder => ShellActionKind::ExtractToFolder,
        }
    }

    pub(crate) fn supports_count(self, count: u32) -> bool {
        if count == 0 {
            return false;
        }
        match self {
            Self::Open => count == 1,
            Self::ExtractToFolder => count == 1,
            _ => true,
        }
    }
}
