import { existsSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, readlinkSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";

/**
 * Locating, describing, and cleaning up the shared archive fixture corpus.
 *
 * The corpus lives in the sibling `zmanager` checkout, not in this repository.
 * `scripts/ensure-sibling-repos.sh` provisions it in CI; locally it is present
 * whenever both repositories are checked out next to each other.
 */

export type FixtureManifestEntry = {
  filename: string;
  format: string;
  extract: boolean;
  password: string | null;
  sha256: string;
  notes: string;
};

export type ExpectedEntry = {
  path: string;
  kind: "file" | "directory" | "symlink" | "hardlink" | "special";
};

/** Repository root, resolved from this file rather than the process cwd. */
const REPO_ROOT = path.resolve(import.meta.dirname, "..", "..", "..");

export const FIXTURE_ARCHIVES_DIR = path.resolve(REPO_ROOT, "..", "zmanager", "fixtures", "archives");

/**
 * Whether the sibling fixture corpus is available.
 *
 * Specs must consult this and mark themselves pending with
 * {@link missingCorpusReason} rather than passing silently: a green run that
 * quietly skipped every archive assertion is worse than a red one.
 */
export function hasFixtureCorpus(): boolean {
  return existsSync(path.join(FIXTURE_ARCHIVES_DIR, "manifest.tsv"));
}

export function missingCorpusReason(): string {
  return (
    `archive fixture corpus not found at ${FIXTURE_ARCHIVES_DIR}. ` +
    "Check out the sibling zmanager repository, or run scripts/ensure-sibling-repos.sh."
  );
}

export function fixturePath(filename: string): string {
  return path.join(FIXTURE_ARCHIVES_DIR, filename);
}

/**
 * Parses `manifest.tsv`, the authoritative list of corpus fixtures.
 *
 * Reading the manifest instead of globbing the directory keeps this suite
 * aligned with the corpus owner: a fixture added there is picked up here
 * automatically, and a stray file on disk does not silently become a test case.
 */
export function fixtureManifest(): FixtureManifestEntry[] {
  const manifest = readFileSync(path.join(FIXTURE_ARCHIVES_DIR, "manifest.tsv"), "utf8");
  const entries = manifest
    .split("\n")
    .filter((line) => line.trim().length > 0 && !line.startsWith("#"))
    .map((line) => {
      const fields = line.split("\t");
      if (fields.length < 6) {
        throw new Error(`invalid fixture manifest line: ${JSON.stringify(line)}`);
      }
      return {
        filename: fields[0],
        format: fields[1],
        extract: fields[2] === "true",
        password: fields[3].length > 0 ? fields[3] : null,
        sha256: fields[4],
        notes: fields[5],
      } satisfies FixtureManifestEntry;
    });

  if (entries.length === 0) {
    throw new Error(`fixture manifest is empty: ${FIXTURE_ARCHIVES_DIR}`);
  }
  return entries;
}

/**
 * Fixture formats that cannot be exercised on the running platform.
 *
 * Mirrors `fixture_supported_on_target` in the zmanager CLI fixture tests: the
 * MTREE reader is Unix-only and Apple Archive is Apple-only.
 */
export function fixtureSupportedOnPlatform(fixture: FixtureManifestEntry): boolean {
  if (fixture.format === "MTREE" && process.platform === "win32") {
    return false;
  }
  if (fixture.format === "AAR" && process.platform !== "darwin") {
    return false;
  }
  return true;
}

/**
 * The shared `payload/` tree every container fixture is generated from, minus
 * the symlink. See `fixtures/archives/README.md` in the zmanager repository.
 *
 * The symlink is supplied per format by {@link payloadTree}, because formats
 * disagree on whether they can represent one.
 */
const PAYLOAD_TREE_WITHOUT_SYMLINK: readonly ExpectedEntry[] = [
  { path: "payload", kind: "directory" },
  { path: "payload/README.txt", kind: "file" },
  { path: "payload/nested", kind: "directory" },
  { path: "payload/nested/file.txt", kind: "file" },
  { path: "payload/nested/empty-dir", kind: "directory" },
  { path: "payload/dir with spaces", kind: "directory" },
  { path: "payload/dir with spaces/file with spaces.txt", kind: "file" },
  { path: "payload/unicode", kind: "directory" },
  { path: "payload/unicode/こんにちは.txt", kind: "file" },
];

/**
 * The full shared payload tree, recording the symlink member as the kind the
 * given format is expected to report: `"symlink"` where the format preserves
 * it, `"file"` where the writer materializes it instead.
 */
export function payloadTree(symlinkKind: ExpectedEntry["kind"]): ExpectedEntry[] {
  return [...PAYLOAD_TREE_WITHOUT_SYMLINK, { path: "payload/nested/readme-link.txt", kind: symlinkKind }];
}

/**
 * Entries the corpus may carry beyond the documented tree.
 *
 * Fixtures generated by bsdtar on macOS contain AppleDouble sidecars, because
 * the corpus generator sets `COPYFILE_DISABLE=1` for only one of its archives.
 * They are host artifacts rather than fixture content — a Linux regeneration
 * omits them — so entry counts are host-dependent and these are ignored rather
 * than asserted. Cleaning the corpus is tracked in the zmanager repository;
 * ignoring them here keeps this suite passing either way.
 */
export function isGenerationArtifact(entryPath: string): boolean {
  const leaf = entryPath.split("/").pop() ?? "";
  return leaf.startsWith("._");
}

export type DiskEntry = {
  path: string;
  kind: "file" | "directory" | "symlink";
  /** File contents; omitted for directories and symlinks. */
  contents?: string;
  /** Symlink target, verbatim; omitted otherwise. */
  target?: string;
};

/**
 * Reads a directory tree into a comparable map, keyed by path relative to
 * `root` with forward slashes on every platform.
 *
 * Uses `lstat`, never `stat`: following links would make a symlink and its
 * target indistinguishable, which is exactly the distinction several format
 * expectations turn on. Generation artifacts are skipped so a corpus built on
 * macOS compares equal to one built on Linux.
 */
export function readTree(root: string): Map<string, DiskEntry> {
  const entries = new Map<string, DiskEntry>();

  const walk = (directory: string, prefix: string): void => {
    for (const child of readdirSync(directory, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      const relativePath = prefix.length > 0 ? `${prefix}/${child.name}` : child.name;
      const absolutePath = path.join(directory, child.name);
      if (isGenerationArtifact(relativePath)) {
        continue;
      }

      const stats = lstatSync(absolutePath);
      if (stats.isSymbolicLink()) {
        entries.set(relativePath, { path: relativePath, kind: "symlink", target: readlinkSync(absolutePath) });
        continue;
      }
      if (stats.isDirectory()) {
        entries.set(relativePath, { path: relativePath, kind: "directory" });
        walk(absolutePath, relativePath);
        continue;
      }
      entries.set(relativePath, { path: relativePath, kind: "file", contents: readFileSync(absolutePath, "utf8") });
    }
  };

  walk(root, "");
  return entries;
}

/**
 * Compares two on-disk trees and returns human-readable differences.
 *
 * Returns every difference rather than the first, because a format that
 * mangles one name usually mangles several and fixing them one run at a time
 * is slow.
 */
export function diffTrees(expected: Map<string, DiskEntry>, actual: Map<string, DiskEntry>): string[] {
  const differences: string[] = [];

  for (const [entryPath, expectedEntry] of expected) {
    const actualEntry = actual.get(entryPath);
    if (!actualEntry) {
      differences.push(`missing ${entryPath}`);
      continue;
    }
    if (actualEntry.kind !== expectedEntry.kind) {
      differences.push(`${entryPath}: kind ${actualEntry.kind}, expected ${expectedEntry.kind}`);
      continue;
    }
    if (expectedEntry.kind === "file" && actualEntry.contents !== expectedEntry.contents) {
      differences.push(`${entryPath}: contents ${JSON.stringify(actualEntry.contents)}, expected ${JSON.stringify(expectedEntry.contents)}`);
    }
    if (expectedEntry.kind === "symlink" && actualEntry.target !== expectedEntry.target) {
      differences.push(`${entryPath}: link target ${JSON.stringify(actualEntry.target)}, expected ${JSON.stringify(expectedEntry.target)}`);
    }
  }

  for (const entryPath of actual.keys()) {
    if (!expected.has(entryPath)) {
      differences.push(`unexpected ${entryPath}`);
    }
  }

  return differences;
}

/**
 * Builds a source tree mirroring the fixture corpus payload, for round-trip
 * tests that create an archive and read it back.
 *
 * Built at test time rather than copied from the corpus so the round trip
 * owns its input: it stays valid while the corpus is being cleaned up in the
 * zmanager repository.
 */
export function writePayloadSourceTree(root: string, options: { withSymlink: boolean } = { withSymlink: true }): string {
  const payload = path.join(root, "payload");
  mkdirSync(path.join(payload, "nested", "empty-dir"), { recursive: true });
  mkdirSync(path.join(payload, "dir with spaces"), { recursive: true });
  mkdirSync(path.join(payload, "unicode"), { recursive: true });

  writeFileSync(path.join(payload, "README.txt"), "ZManager fixture payload\n");
  writeFileSync(path.join(payload, "nested", "file.txt"), "nested fixture file\n");
  writeFileSync(path.join(payload, "dir with spaces", "file with spaces.txt"), "spaces in path\n");
  writeFileSync(path.join(payload, "unicode", "こんにちは.txt"), "unicode path fixture\n");

  if (options.withSymlink) {
    symlinkSync("../README.txt", path.join(payload, "nested", "readme-link.txt"));
  }

  return payload;
}

/** Creates an isolated temporary directory, returning it with a disposer. */
export function makeTempDir(label: string): { dir: string; cleanup: (keep: boolean) => void } {
  const dir = mkdtempSync(path.join(os.tmpdir(), `zmanager-gui-${label}-`));
  return {
    dir,
    cleanup(keep: boolean) {
      // Failed runs keep their output: diagnosing a bad extraction without the
      // resulting tree is guesswork.
      if (keep) {
        console.log(`retained ${label} output for inspection: ${dir}`);
        return;
      }
      rmSync(dir, { recursive: true, force: true });
    },
  };
}
