import { describe, expect, it } from "vitest";

const nativeDragPermission = "allow-start-native-file-drag";
const nativeDragCommand = "start_native_file_drag";

declare const process: {
  cwd(): string;
};

declare function require(id: "fs"): {
  existsSync(path: string): boolean;
  readFileSync(path: string, encoding: string): string;
};

declare function require(id: "path"): {
  join(...parts: string[]): string;
};

const { existsSync, readFileSync } = require("fs");
const { join } = require("path");

function readWorkspaceFile(...parts: string[]): string {
  return readFileSync(join(process.cwd(), ...parts), "utf8");
}

describe("Tauri command capabilities", () => {
  it("allows native file drag from the main window capability", () => {
    const capability = JSON.parse(
      readWorkspaceFile("src-tauri", "capabilities", "default.json"),
    ) as { permissions: Array<string | { identifier: string }> };

    const permissionIds = capability.permissions.map((permission) =>
      typeof permission === "string" ? permission : permission.identifier,
    );

    expect(permissionIds).toContain(nativeDragPermission);
  });

  it("defines the native file drag command permission", () => {
    const permissionPath = join(
      process.cwd(),
      "src-tauri",
      "permissions",
      "autogenerated",
      "start_native_file_drag.toml",
    );

    expect(existsSync(permissionPath)).toBe(true);

    const permissionFile = readFileSync(permissionPath, "utf8");
    expect(permissionFile).toContain(`identifier = "${nativeDragPermission}"`);
    expect(permissionFile).toContain(`commands.allow = ["${nativeDragCommand}"]`);
  });

  it("includes native file drag in the generated app ACL snapshot", () => {
    const generatedAclPath = join(
      process.cwd(),
      "src-tauri",
      "gen",
      "schemas",
      "acl-manifests.json",
    );
    if (!existsSync(generatedAclPath)) {
      return;
    }

    const acl = JSON.parse(
      readFileSync(generatedAclPath, "utf8"),
    ) as {
      "__app-acl__": {
        permissions: Record<
          string,
          { commands: { allow: string[]; deny: string[] } }
        >;
      };
    };

    expect(acl["__app-acl__"].permissions[nativeDragPermission]?.commands.allow)
      .toContain(nativeDragCommand);
  });
});
