[[permission]]
identifier = "allow-clear-native-file-drag"
description = "Enables the clear_native_file_drag command without any pre-configured scope."
commands.allow = ["clear_native_file_drag"]

[[permission]]
identifier = "deny-clear-native-file-drag"
description = "Denies the clear_native_file_drag command without any pre-configured scope."
commands.deny = ["clear_native_file_drag"]
