// Generated by scripts/generate-native-contracts.mjs. Do not edit.
public enum ArchiveFileTypes {
    public static let singleExtensions: [String] = ["7z", "a", "aar", "aea", "apk", "appx", "ar", "b64", "br", "bz2", "cab", "cb7", "cbr", "cbt", "cbz", "cpgz", "cpio", "deb", "dmg", "epub", "gz", "ipa", "iso", "jar", "lha", "lib", "lz", "lz4", "lzh", "lzma", "lzo", "msi", "mtree", "pax", "pkg", "rar", "rpm", "sevenz", "tar", "taz", "tbz", "tbz2", "tgz", "tlzma", "txz", "tzap", "tzst", "udf", "ustar", "uu", "vhd", "vmdk", "war", "warc", "xar", "xpi", "xz", "z", "zip", "zipx", "zst"]
    public static let compoundExtensions: [String] = ["cpio.bz2", "cpio.gz", "cpio.lzma", "cpio.xz", "cpio.zst", "tar.b64", "tar.br", "tar.bz2", "tar.gz", "tar.lrz", "tar.lz", "tar.lz4", "tar.lzma", "tar.lzo", "tar.uu", "tar.xz", "tar.z", "tar.zst"]
    public static let splitArchiveSuffixes: [String] = [".7z.001", ".vol000.tzap"]
}
