// Generated by scripts/generate-native-contracts.mjs. Do not edit.
public enum ArchiveFileTypes {
    public static let singleExtensions: [String] = ["7z", "a", "aar", "aea", "apk", "appx", "ar", "br", "bz2", "cab", "cb7", "cbr", "cbt", "cbz", "cpio", "deb", "epub", "gz", "ipa", "iso", "jar", "lha", "lrz", "lz", "lz4", "lzh", "lzma", "lzo", "msi", "mtree", "rar", "rpm", "tar", "tbz", "tbz2", "tgz", "tlzma", "txz", "tzap", "tzst", "war", "xar", "xpi", "xz", "z", "zip", "zipx", "zst"]
    public static let compoundExtensions: [String] = ["tar.br", "tar.bz2", "tar.gz", "tar.lrz", "tar.lz", "tar.lz4", "tar.lzma", "tar.lzo", "tar.xz", "tar.z", "tar.zst"]
    public static let splitArchiveSuffixes: [String] = [".7z.001", ".vol000.tzap"]
}
