// Generated by scripts/generate-native-contracts.mjs. Do not edit.
public let nativeInboundEventVersion = 1
public enum NativeInboundEventKind: String, Codable, CaseIterable, Sendable {
    case openPaths
    case shellActionRequest
    case hostedAuthCallback
    case reopenApplication
}
