// Generated by scripts/generate-native-contracts.mjs. Do not edit.
public enum ShellActionID: String, Codable, CaseIterable, Sendable {
    case `open`
    case compress
    case extract
    case compressZip
    case compressTzap
    case compressSevenZ
    case compressTarZst
    case compressCleanSource
    case extractHere
    case extractToFolder
}
public struct ShellActionPolicy: Equatable, Sendable {
    public let id: ShellActionID
    public let displayKey: String
    public let order: Int
    public let selectionShapes: [String]
    public let multiplicity: String
    public static let all: [ShellActionPolicy] = [
        .init(id: .open, displayKey: "shellAction.open", order: 10, selectionShapes: ["single-archive"], multiplicity: "exactly-one"),
        .init(id: .compress, displayKey: "shellAction.compress", order: 20, selectionShapes: ["files", "folders", "mixed"], multiplicity: "one-or-more"),
        .init(id: .extract, displayKey: "shellAction.extract", order: 30, selectionShapes: ["single-archive", "multiple-archives"], multiplicity: "one-or-more"),
        .init(id: .compressZip, displayKey: "shellAction.compressZip", order: 40, selectionShapes: ["files", "folders", "mixed"], multiplicity: "one-or-more"),
        .init(id: .compressTzap, displayKey: "shellAction.compressTzap", order: 50, selectionShapes: ["files", "folders", "mixed"], multiplicity: "one-or-more"),
        .init(id: .compressSevenZ, displayKey: "shellAction.compressSevenZ", order: 60, selectionShapes: ["files", "folders", "mixed"], multiplicity: "one-or-more"),
        .init(id: .compressTarZst, displayKey: "shellAction.compressTarZst", order: 70, selectionShapes: ["files", "folders", "mixed"], multiplicity: "one-or-more"),
        .init(id: .compressCleanSource, displayKey: "shellAction.compressCleanSource", order: 80, selectionShapes: ["single-folder"], multiplicity: "exactly-one"),
        .init(id: .extractHere, displayKey: "shellAction.extractHere", order: 90, selectionShapes: ["single-archive", "multiple-archives"], multiplicity: "one-or-more"),
        .init(id: .extractToFolder, displayKey: "shellAction.extractToFolder", order: 100, selectionShapes: ["single-archive"], multiplicity: "exactly-one")
    ]
}
