// Generated by scripts/generate-native-contracts.mjs. Do not edit.
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum ShellActionKind {
    Open,
    Compress,
    Extract,
    CompressZip,
    CompressTzap,
    CompressSevenZ,
    CompressTarZst,
    CompressTarGz,
    CompressCleanSource,
    ExtractHere,
    ExtractToFolder,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ShellActionPolicy {
    pub kind: ShellActionKind,
    pub id: &'static str,
    pub display_key: &'static str,
    pub order: u16,
    pub selection_shapes: &'static [&'static str],
    pub multiplicity: &'static str,
}

pub const SHELL_ACTION_POLICIES: &[ShellActionPolicy] = &[
    ShellActionPolicy {
        kind: ShellActionKind::Open,
        id: "open",
        display_key: "shellAction.open",
        order: 10,
        selection_shapes: &["single-archive"],
        multiplicity: "exactly-one",
    },
    ShellActionPolicy {
        kind: ShellActionKind::Compress,
        id: "compress",
        display_key: "shellAction.compress",
        order: 20,
        selection_shapes: &["files", "folders", "mixed"],
        multiplicity: "one-or-more",
    },
    ShellActionPolicy {
        kind: ShellActionKind::Extract,
        id: "extract",
        display_key: "shellAction.extract",
        order: 30,
        selection_shapes: &["single-archive", "multiple-archives"],
        multiplicity: "one-or-more",
    },
    ShellActionPolicy {
        kind: ShellActionKind::CompressZip,
        id: "compressZip",
        display_key: "shellAction.compressZip",
        order: 40,
        selection_shapes: &["files", "folders", "mixed"],
        multiplicity: "one-or-more",
    },
    ShellActionPolicy {
        kind: ShellActionKind::CompressTzap,
        id: "compressTzap",
        display_key: "shellAction.compressTzap",
        order: 50,
        selection_shapes: &["files", "folders", "mixed"],
        multiplicity: "one-or-more",
    },
    ShellActionPolicy {
        kind: ShellActionKind::CompressSevenZ,
        id: "compressSevenZ",
        display_key: "shellAction.compressSevenZ",
        order: 60,
        selection_shapes: &["files", "folders", "mixed"],
        multiplicity: "one-or-more",
    },
    ShellActionPolicy {
        kind: ShellActionKind::CompressTarZst,
        id: "compressTarZst",
        display_key: "shellAction.compressTarZst",
        order: 70,
        selection_shapes: &["files", "folders", "mixed"],
        multiplicity: "one-or-more",
    },
    ShellActionPolicy {
        kind: ShellActionKind::CompressTarGz,
        id: "compressTarGz",
        display_key: "shellAction.compressTarGz",
        order: 75,
        selection_shapes: &["files", "folders", "mixed"],
        multiplicity: "one-or-more",
    },
    ShellActionPolicy {
        kind: ShellActionKind::CompressCleanSource,
        id: "compressCleanSource",
        display_key: "shellAction.compressCleanSource",
        order: 80,
        selection_shapes: &["single-folder"],
        multiplicity: "exactly-one",
    },
    ShellActionPolicy {
        kind: ShellActionKind::ExtractHere,
        id: "extractHere",
        display_key: "shellAction.extractHere",
        order: 90,
        selection_shapes: &["single-archive", "multiple-archives"],
        multiplicity: "one-or-more",
    },
    ShellActionPolicy {
        kind: ShellActionKind::ExtractToFolder,
        id: "extractToFolder",
        display_key: "shellAction.extractToFolder",
        order: 100,
        selection_shapes: &["single-archive"],
        multiplicity: "exactly-one",
    },
];
