#!/usr/bin/env python3
"""Generate the third-party license bundle used by ZManager releases."""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
from pathlib import Path

WORKSPACE_NOTICE = "Generated by scripts/generate-third-party-notices.py. Do not edit release copies by hand."
COMMON_LICENSE_NAMES = re.compile(r"^(license|licence|copying|notice)(\.|$)", re.IGNORECASE)
VCPKG_PORTS = ("zlib", "bzip2", "liblzma", "zstd", "lz4", "openssl")
ALLOWED_NPM_LICENSES = {
    "0BSD",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BlueOak-1.0.0",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MIT-0",
    "MPL-2.0",
    "Unlicense",
    "Zlib",
}


def parse_args() -> argparse.Namespace:
    workspace = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--workspace", type=Path, default=workspace)
    parser.add_argument("--manifest-path", type=Path, default=None)
    parser.add_argument("--npm-lock", type=Path, default=None)
    parser.add_argument("--out-notices", type=Path, default=None)
    parser.add_argument("--license-dir", type=Path, default=None)
    parser.add_argument("--vcpkg-root", type=Path, default=None)
    parser.add_argument("--vcpkg-triplet", default=None)
    parser.add_argument(
        "--check-npm",
        action="store_true",
        help="Fail when a production npm dependency uses an unreviewed SPDX identifier.",
    )
    return parser.parse_args()


def run_metadata(workspace: Path, manifest_path: Path) -> dict:
    output = subprocess.check_output(
        [
            "cargo",
            "metadata",
            "--format-version",
            "1",
            "--locked",
            "--manifest-path",
            str(manifest_path),
        ],
        cwd=workspace,
        text=True,
        encoding="utf-8",
    )
    return json.loads(output)


def markdown_escape(value: str | None) -> str:
    if not value:
        return ""
    return value.replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ")


def display_path(path: Path, notice_path: Path) -> str:
    return path.relative_to(notice_path.parent).as_posix()


def copy_file(source: Path, destination: Path) -> Path:
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, destination)
    return destination


def package_dir_name(name: str, version: str) -> str:
    return f"{name.replace('/', '_')}-{version.replace('/', '_')}"


def candidate_license_files(package_root: Path, license_file: str | None = None) -> list[Path]:
    candidates: list[Path] = []
    if license_file:
        candidates.append((package_root / license_file).resolve())
    if package_root.is_dir():
        candidates.extend(
            path.resolve()
            for path in package_root.iterdir()
            if path.is_file() and COMMON_LICENSE_NAMES.match(path.name)
        )

    unique: list[Path] = []
    seen: set[Path] = set()
    for candidate in candidates:
        if candidate.is_file() and candidate not in seen:
            unique.append(candidate)
            seen.add(candidate)
    return unique


def collect_rust_crates(metadata: dict, license_dir: Path, notice_path: Path) -> list[dict]:
    package_by_id = {package["id"]: package for package in metadata["packages"]}
    workspace_members = set(metadata["workspace_members"])
    resolved_ids = {node["id"] for node in metadata["resolve"]["nodes"]}
    crates: list[dict] = []

    for package_id in sorted(resolved_ids):
        package = package_by_id[package_id]
        if package_id in workspace_members:
            continue

        manifest = Path(package["manifest_path"])
        license_files = candidate_license_files(manifest.parent, package.get("license_file"))
        is_registry_package = str(package.get("source", "")).startswith("registry+")
        # Path dependencies outside this workspace can still carry bundled
        # third-party source, such as zmanager-unrar's license-file.
        if not is_registry_package and not license_files:
            continue

        destination_root = license_dir / "rust" / package_dir_name(package["name"], package["version"])
        copied_files = [
            display_path(copy_file(source, destination_root / source.name), notice_path)
            for source in license_files
        ]
        crates.append(
            {
                "name": package["name"],
                "version": package["version"],
                "license": package.get("license") or ("UnRAR freeware license" if package["name"] == "zmanager-unrar" else "See copied license files"),
                "license_files": copied_files,
            }
        )

    return sorted(crates, key=lambda item: (item["name"], item["version"]))


def npm_package_name(package_path: str, package: dict, package_json: dict) -> str:
    if package_json.get("name"):
        return package_json["name"]
    return package_path.removeprefix("node_modules/")


def load_npm_packages(workspace: Path, lock_path: Path) -> list[dict]:
    lock = json.loads(lock_path.read_text(encoding="utf-8"))
    packages: list[dict] = []
    for package_path, lock_package in lock.get("packages", {}).items():
        if not package_path.startswith("node_modules/") or lock_package.get("dev"):
            continue
        package_root = workspace / package_path
        package_json_path = package_root / "package.json"
        package_json = json.loads(package_json_path.read_text(encoding="utf-8")) if package_json_path.is_file() else {}
        name = npm_package_name(package_path, lock_package, package_json)
        version = str(lock_package.get("version") or package_json.get("version") or "unknown")
        license_expression = lock_package.get("license") or package_json.get("license") or "UNKNOWN"
        packages.append(
            {
                "name": name,
                "version": version,
                "license": license_expression,
                "root": package_root,
            }
        )
    return sorted(packages, key=lambda item: (item["name"], item["version"]))


def validate_npm_licenses(packages: list[dict]) -> None:
    failures: list[str] = []
    for package in packages:
        identifiers = set(re.findall(r"[A-Za-z0-9][A-Za-z0-9.+-]*", package["license"]))
        identifiers -= {"AND", "OR", "WITH"}
        unknown = sorted(identifier for identifier in identifiers if identifier not in ALLOWED_NPM_LICENSES)
        if unknown:
            failures.append(f"{package['name']}@{package['version']}: {package['license']} (unreviewed: {', '.join(unknown)})")
    if failures:
        raise RuntimeError("Unreviewed production npm licenses:\n" + "\n".join(f"- {failure}" for failure in failures))


def collect_npm_packages(workspace: Path, lock_path: Path, license_dir: Path, notice_path: Path, check: bool) -> list[dict]:
    packages = load_npm_packages(workspace, lock_path)
    if check:
        validate_npm_licenses(packages)

    for package in packages:
        destination_root = license_dir / "npm" / package_dir_name(package["name"], package["version"])
        package["license_files"] = [
            display_path(copy_file(source, destination_root / source.name), notice_path)
            for source in candidate_license_files(package["root"], None)
        ]
        del package["root"]
    return packages


def resolve_vcpkg_root(explicit_root: Path | None) -> Path | None:
    if explicit_root:
        return explicit_root
    for key in ("VCPKG_INSTALLATION_ROOT", "VCPKG_ROOT"):
        if os.environ.get(key):
            return Path(os.environ[key])
    return None


def collect_vcpkg_notices(license_dir: Path, notice_path: Path, root: Path | None, triplet: str | None) -> list[dict]:
    if root is None or not triplet:
        return []
    notices: list[dict] = []
    for port in VCPKG_PORTS:
        copyright_file = root / "installed" / triplet / "share" / port / "copyright"
        if not copyright_file.is_file():
            continue
        copied = copy_file(copyright_file, license_dir / "native" / "vcpkg" / port / "copyright")
        notices.append({"name": port, "triplet": triplet, "license_files": [display_path(copied, notice_path)]})
    return notices


def format_license_files(files: list[str]) -> str:
    return "<br>".join(f"`{path}`" for path in files) if files else "Metadata only; no license file found"


def render_notices(
    rust_crates: list[dict],
    npm_packages: list[dict],
    vcpkg_notices: list[dict],
) -> str:
    lines = [
        "# Third-Party Notices",
        "",
        WORKSPACE_NOTICE,
        "",
        "This file is generated for ZManager Desktop release artifacts.",
        "The copied license texts are shipped beside this notice under",
        "`third-party-licenses/`.",
        "",
        "## ZManager Desktop",
        "",
        "- License: Apache-2.0",
        "- License file: LICENSE",
        "",
        "## Native Package Manager Licenses",
        "",
    ]
    if vcpkg_notices:
        lines.extend(["| Package | Triplet | License file |", "| --- | --- | --- |"])
        for notice in vcpkg_notices:
            lines.append(f"| {notice['name']} | {notice['triplet']} | {format_license_files(notice['license_files'])} |")
        lines.append("")
    else:
        lines.extend(["No vcpkg license files were detected in this generation environment.", ""])

    lines.extend([
        "## Vendored and Rust Dependencies",
        "",
        "The inventory below includes resolved registry crates and path dependencies",
        "that carry their own bundled license files.",
        "",
        "| Crate | Version | License metadata | License files |",
        "| --- | --- | --- | --- |",
    ])
    for crate in rust_crates:
        lines.append(f"| {markdown_escape(crate['name'])} | {crate['version']} | {markdown_escape(crate['license'])} | {format_license_files(crate['license_files'])} |")

    lines.extend([
        "",
        "## Frontend Dependencies",
        "",
        "This inventory contains production packages resolved by package-lock.json.",
        "",
        "| Package | Version | License metadata | License files |",
        "| --- | --- | --- | --- |",
    ])
    for package in npm_packages:
        lines.append(f"| {markdown_escape(package['name'])} | {package['version']} | {markdown_escape(package['license'])} | {format_license_files(package['license_files'])} |")

    lines.extend([
        "",
        "## Generation Inputs",
        "",
        "- Cargo command: `cargo metadata --format-version 1 --locked`",
        "- Rust manifest: `src-tauri/Cargo.toml`",
        "- npm input: `package-lock.json` production dependency closure",
        "- Native input: vcpkg `share/*/copyright` files when available",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    args = parse_args()
    workspace = args.workspace.resolve()
    manifest_path = (args.manifest_path or workspace / "src-tauri" / "Cargo.toml").resolve()
    lock_path = (args.npm_lock or workspace / "package-lock.json").resolve()
    notice_path = (args.out_notices or workspace / "THIRD_PARTY_NOTICES.md").resolve()
    license_dir = (args.license_dir or workspace / "third-party-licenses").resolve()

    metadata = run_metadata(workspace, manifest_path)
    if license_dir.exists():
        shutil.rmtree(license_dir)
    license_dir.mkdir(parents=True)

    rust_crates = collect_rust_crates(metadata, license_dir, notice_path)
    npm_packages = collect_npm_packages(workspace, lock_path, license_dir, notice_path, args.check_npm)
    vcpkg_notices = collect_vcpkg_notices(
        license_dir,
        notice_path,
        resolve_vcpkg_root(args.vcpkg_root),
        args.vcpkg_triplet or os.environ.get("VCPKG_TARGET_TRIPLET") or os.environ.get("VCPKG_DEFAULT_TRIPLET"),
    )
    notice_path.parent.mkdir(parents=True, exist_ok=True)
    notice_path.write_text(render_notices(rust_crates, npm_packages, vcpkg_notices), encoding="utf-8")
    print(notice_path)
    print(license_dir)


if __name__ == "__main__":
    main()
